paths:
  /api/products/:
    get:
      summary: Obtengo todos los productos.
      tags: 
        - Products
      responses:
        "200": 
          description: Operacion exitosa, se retorna data.
        "400":
          description: Operacion fallida.
        "500":
          description: Error inspesperado del servidor, no se concluyo la operación.

  /api/products/createOne:
    post:
      summary: Agregar producto a la base de datos.
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Producto creado exitosamente.
        "400":
          description: Error al crear el producto.
        "500":
          description: Error inspesperado del servidor, no se concluyo la operación.

  /api/products/findOne/{pid}:
    get:
      summary: Buscar producto por id.
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea solicitar.
        schema:
          type: string
      responses:
        "200":
          description: Producto encontrado con exito.
        "400":
          description: Error al obtener producto.
        "500":
          description: Error inspesperado del servidor, no se concluyo la operación.

  /api/products/updateOne/{pid}:
    put:
      summary: Modificar o actualizar producto.
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea modificar.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Producto encontrado y modificado con exito.
        "400":
          description: Error al obtener producto o modificarlo.
        "500":
          description: Error inspesperado del servidor, no se concluyo la operación.

  /api/products/deleteOne/{pid}:
    delete:
      summary: Eliminar producto por id.
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea eliminar.
        schema:
          type: string
      responses:
        "200":
          description: Producto eliminado con exito.
        "400":
          description: Error al obtener producto.
        "500":
          description: Error inspesperado del servidor, no se concluyo la operación.


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: object_id
          description: Id autogenerado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: Url de la imagen del producto
        stock:
          type: number
          description: Cantidad de productos en stock
        updatedAt:
          type: string
          description: Fecha autogenerada por MongoDB
      example:
          _id: "64ee2366ec71e4c0df0ba3f9",
        title: "Discos",
        description: "Disco Sólido SSD Kingston 240GB A400 500MB/s",
        price: 16610,
        stock: 5,
        category: "Almacenamiento",
        thumbnails: "https://compragamer.net/pga/imagenes_publicadas/compragamer_Imganen_general_9269_Disco_S__lido_SSD_Kingston_240GB_A400_500MB_s_c9de3151-grn.jpg",
        __v: 0